### ISSUE TITLE
Add Basic Features

### ISSUE THREAD

**Issue by s0LA1337** [s0LA1337/Antario-Blankware-Base#2]
Such as Aimbot, Anti Aims, Resolver, RCS, ...

**Comment by certmemer** [comment]
are you sure thats how you are supposed to use github?

**Comment by Wando1423** [comment]
@certmemer no bully
@s0LA1337 use project builder, works much better if you want to make yourself some milestones :)

**Comment by s0LA1337** [comment]
Thanks, i don't use Github at all :p
